import { useState } from "react";
import { calculateTax, compareTax } from "../../../lib/tax/calculate";
import type { TaxResult } from "../../../lib/tax/types";
import { money, signedMoney, percentage } from "./presentation";
import styles from "./tax.module.css";
function annualScenario(base: TaxResult, income: string) {
  try { return calculateTax({ ...base.input, income, frequency: "annual" }); } catch { return null; }
}
function ScenarioTotals({ result, label }: { result: TaxResult; label: string }) {
  return <div className={styles.scenarioCard}><span className={styles.kicker}>{label}</span><strong className={styles.scenarioAmount}>{money(result.annualGrossCents)}</strong><span className={styles.helper}>Annual gross income</span><dl className={styles.scenarioList}><div><dt>Tax + Medicare</dt><dd>{money(result.deductionsCents)}</dd></div><div><dt>Take-home</dt><dd className={styles.green}>{money(result.netCents)}</dd></div><div><dt>Effective rate</dt><dd>{percentage(result.effectiveRate)}</dd></div></dl></div>;
}
export function PayRise({ base }: { base: TaxResult }) {
  const [mode, setMode] = useState("5000"), [custom, setCustom] = useState("7500");
  const amount = mode === "5%" ? base.annualGrossCents * 0.05 : mode === "10%" ? base.annualGrossCents * 0.1 : Number(mode === "custom" ? custom : mode) * 100;
  const valid = Number.isFinite(amount) && amount >= 0 && /^\d+(\.\d{1,2})?$/.test(mode === "custom" ? custom : "0");
  const raised = valid ? annualScenario(base, ((base.annualGrossCents + Math.round(amount)) / 100).toFixed(2)) : null;
  const delta = raised ? compareTax(base, raised) : null;
  return <section className={styles.card} id="tax-pay-rise" aria-labelledby="raise-heading" data-glow="true"><div className={styles.sectionLabel}><span>05 / YOUR NEXT MOVE</span><span>PAY-RISE LAB</span></div><h2 id="raise-heading">What if you earned more?</h2><p className={styles.intro}>Explore how much of a raise reaches your pocket. All comparisons use the same year and assumptions.</p><div className={styles.segments} role="group" aria-label="Salary increase">{["1000", "5000", "10000", "5%", "10%", "custom"].map(value => <button type="button" key={value} aria-pressed={mode === value} onClick={() => setMode(value)}>{value === "custom" ? "Custom" : value.includes("%") ? `+${value}` : `+${money(Number(value) * 100)}`}</button>)}</div>{mode === "custom" && <label className={styles.singleField}>Annual gross increase ($)<input type="text" inputMode="decimal" maxLength={12} value={custom} onChange={event => setCustom(event.target.value)} /></label>}
    {raised && delta ? <><div className={styles.twoColumns}><ScenarioTotals result={base} label="CURRENT INCOME" /><ScenarioTotals result={raised} label="AFTER YOUR RAISE" /></div><div className={styles.deltaGrid}><div><span>Gross increase</span><strong>{signedMoney(delta.gross)}</strong></div><div><span>Additional tax + levy</span><strong>{signedMoney(delta.deductions)}</strong></div><div><span>Extra in your pocket / year</span><strong className={styles.green}>{signedMoney(delta.net)}</strong></div></div><div className={styles.comparisonBars}>{[{ label: "Current take-home", value: base.netCents }, { label: "After your raise", value: raised.netCents }].map(row => <div key={row.label}><span>{row.label}</span><div className={styles.track}><span className={styles.freeFill} style={{ width: `${raised.netCents ? row.value / raised.netCents * 100 : 0}%` }} /></div><strong>{money(row.value)}</strong></div>)}</div></> : <p className={styles.error} role="alert">Enter a valid increase. Total annual income must stay within $10,000,000.</p>}
  </section>;
}
export function IncomeComparison({ base }: { base: TaxResult }) {
  const [offer, setOffer] = useState("100000");
  const comparison = annualScenario(base, offer), delta = comparison ? compareTax(base, comparison) : null;
  return <section className={styles.card} aria-labelledby="comparison-heading" data-glow="true"><div className={styles.sectionLabel}><span>06 / SIDE BY SIDE</span><span>OFFER COMPARISON</span></div><h2 id="comparison-heading">Compare two incomes</h2><p className={styles.intro}>The salary on an offer and the amount you keep tell different stories.</p><label className={styles.singleField}>Comparison annual income ($)<input type="text" inputMode="decimal" maxLength={15} value={offer} onChange={event => setOffer(event.target.value)} aria-invalid={!comparison} /></label>{comparison && delta ? <><div className={styles.twoColumns}><ScenarioTotals result={base} label="YOUR CURRENT SCENARIO" /><ScenarioTotals result={comparison} label="COMPARISON SCENARIO" /></div><div className={styles.deltaGrid}><div><span>Gross difference</span><strong>{signedMoney(delta.gross)}</strong></div><div><span>Tax + levy difference</span><strong>{signedMoney(delta.deductions)}</strong></div><div><span>Take-home difference</span><strong className={styles.green}>{signedMoney(delta.net)}</strong></div></div><p className={styles.helper}>Effective deductions rate change: {delta.rate > 0 ? "+" : ""}{delta.rate.toFixed(1)} percentage points. Super and benefits are not included.</p></> : <p className={styles.error} role="alert">Enter an annual income from $0 to $10,000,000 with up to two decimal places.</p>}</section>;
}
export function SalaryConverter({ base }: { base: TaxResult }) {
  const [direction, setDirection] = useState<"hourly" | "annual">("hourly"), [income, setIncome] = useState("45"), [hours, setHours] = useState(38), [weeks, setWeeks] = useState(48);
  let converted: TaxResult | null = null;
  try { converted = calculateTax({ ...base.input, income, frequency: direction, hoursPerWeek: hours, weeksPerYear: weeks }); } catch { /* Inline validation below. */ }
  const hourly = converted ? converted.annualGrossCents / (hours * weeks) : 0;
  return <section className={styles.card} id="tax-converter" aria-labelledby="converter-heading" data-glow="true"><div className={styles.sectionLabel}><span>07 / WORK YOUR WAY</span><span>SALARY CONVERTER</span></div><h2 id="converter-heading">Hourly ↔ salary</h2><p className={styles.intro}>Translate a rate into a year, or see the hourly value of a salary.</p><div className={styles.segments} role="group" aria-label="Conversion direction">{["hourly", "annual"].map(value => <button type="button" key={value} aria-pressed={direction === value} onClick={() => { setDirection(value as typeof direction); setIncome(value === "hourly" ? "45" : (base.annualGrossCents / 100).toFixed(2)); }}>{value === "hourly" ? "Hourly → salary" : "Salary → hourly"}</button>)}</div><div className={styles.converterFields}><label>{direction === "hourly" ? "Hourly rate ($)" : "Annual salary ($)"}<input inputMode="decimal" type="text" maxLength={15} value={income} onChange={event => setIncome(event.target.value)} /></label><label>Hours / week<input type="number" min="1" max="100" step="0.5" value={hours} onChange={event => setHours(Number(event.target.value))} /></label><label>Weeks / year<input type="number" min="1" max="52" step="1" value={weeks} onChange={event => setWeeks(Number(event.target.value))} /></label></div>{converted ? <div className={styles.converterResults}><div><span>Annual gross</span><strong>{money(converted.annualGrossCents)}</strong></div><div><span>Tax + Medicare / year</span><strong>{money(converted.deductionsCents)}</strong></div><div><span>Take-home / year</span><strong className={styles.green}>{money(converted.netCents)}</strong></div><div><span>Gross / working hour</span><strong>{money(Math.round(hourly))}</strong></div></div> : <p className={styles.error} role="alert">Check your amount, hours (1–100 in half-hour steps) and weeks (1–52). Annualised income must not exceed $10,000,000.</p>}<p className={styles.helper}>Assumes the rate is earned for every entered working hour. Leave, overtime, benefits and super are not added. The converter does not change your main calculation.</p></section>;
}
