"use client";
import Link from "next/link";
import { useState } from "react";
import AppShell from "../components/app-shell";
import { useVault } from "../../lib/use-vault";
import { allocations, categories, financialYear } from "../../lib/domain/tax-record";
import { filterRecords } from "../../lib/domain/vault-filter";
import { hundredths } from "../../lib/domain/invoice-math";
import { money } from "../components/money";
import styles from "../vault.module.css";
export default function RecordsPage() {
  const { documents, loading, error } = useVault();
  const [filters, setFilters] = useState({ year: "", query: "", kind: "", category: "" });
  const [view, setView] = useState<"cards" | "list">("cards"), [selected, setSelected] = useState<string[]>([]);
  const records = filterRecords(documents, filters), review = documents.filter(doc => doc.status === "Review");
  const years = [...new Set(documents.flatMap(doc => doc.record ? [financialYear(doc.record.issued)] : []))].sort().reverse();
  const stats = records.reduce((total, doc) => { const r = doc.record!; if (r.kind === "Expense") total.expense += hundredths(r.total, BigInt(9999999))!; if (r.kind === "Income") total.income += hundredths(r.total, BigInt(9999999))!; total.credit += allocations(r).credit; return total; }, { expense: BigInt(0), income: BigInt(0), credit: BigInt(0) });
  const exportParams = new URLSearchParams(filters); const visibleSelected = selected.filter(id => records.some(doc => doc.id === id)); if (visibleSelected.length) exportParams.set("ids", visibleSelected.join(","));
  return <AppShell title="Every record. A clearer picture." subtitle="Confirmed invoices, original documents, and your tax selections in one traceable view.">
    <div className={styles.titleRow}><span className={styles.tag}>LOCAL POSTGRESQL / AUD</span><div className={styles.actions}><Link href="/upload" className={styles.primary}>+ Upload invoice</Link><a className={styles.secondary} href={`/api/vault/export?${exportParams}`} aria-disabled={loading || !!error || !records.length} onClick={e => { if (loading || error || !records.length) e.preventDefault(); }}>{visibleSelected.length ? `Export ${visibleSelected.length} selected` : "Export filtered records"} ↓ .xlsx</a></div></div>
    {error && <p className={styles.notice} role="alert">{error}</p>}
    <section className={styles.stats} aria-label="Confirmed record totals">{[["Income documents",stats.income],["Expense documents",stats.expense],["GST credit estimate",stats.credit]].map(([label,value]) => <div className={styles.panel} data-glow="true" key={String(label)}><span className={styles.tag}>{String(label)}</span><strong className={styles.statValue}>{money(value as bigint,"AUD")}</strong><small>{label === "GST credit estimate" ? "Only credits selected by you" : "Document totals / invoice-date basis"}</small></div>)}</section>
    {!!review.length && <Link href="/upload" className={styles.reviewBanner}><span className={styles.pulse} /><span><strong>{review.length} document{review.length > 1 ? "s" : ""} waiting for your review</strong><small>These are excluded from records totals and exports.</small></span><span aria-hidden="true">↗</span></Link>}
    <section className={styles.panel} data-glow="true"><div className={styles.filters}><label>Search records<input type="search" placeholder="Supplier, invoice or filename" value={filters.query} onChange={e => setFilters(current => ({ ...current, query: e.target.value }))} /></label><label>Financial year<select value={filters.year} onChange={e => setFilters(current => ({ ...current, year: e.target.value }))}><option value="">All financial years</option>{years.map(year => <option key={year}>{year}</option>)}</select></label><label>Type<select value={filters.kind} onChange={e => setFilters(current => ({ ...current, kind: e.target.value }))}><option value="">All types</option>{["Expense","Income","Personal"].map(kind => <option key={kind}>{kind}</option>)}</select></label><label>Category<select value={filters.category} onChange={e => setFilters(current => ({ ...current, category: e.target.value }))}><option value="">All categories</option>{categories.map(category => <option key={category}>{category}</option>)}</select></label></div><div className={styles.titleRow}><span className={styles.tag}>{records.length} confirmed records · FY 1 July–30 June</span><div className={styles.actions}><button className={styles.secondary} aria-pressed={view === "cards"} onClick={() => setView("cards")}>Cards</button><button className={styles.secondary} aria-pressed={view === "list"} onClick={() => setView("list")}>List</button></div></div>
    {loading ? <p role="status">Opening your records…</p> : !records.length ? <div className={styles.empty}><h2>{documents.some(doc => doc.record) ? "No records match these filters." : "A clear slate. A smarter start."}</h2><p>Upload and confirm an invoice to see real records here.</p><Link href="/upload" className={styles.secondary}>Upload your first invoice ↗</Link></div> : <div className={view === "cards" ? styles.recordGrid : styles.recordList}>{records.map(doc => { const r = doc.record!; return <article className={styles.record} data-glow="true" key={doc.id}><div className={styles.titleRow}><span className={styles.tag}>{r.kind} · {financialYear(r.issued)}</span><label className={styles.selectRecord}><input aria-label={`Select invoice ${r.number}`} type="checkbox" checked={selected.includes(doc.id)} onChange={e => setSelected(current => e.target.checked ? [...current,doc.id] : current.filter(id => id !== doc.id))} />Select</label></div><h3>{r.supplier}</h3><p>{r.number} · {r.issued}</p><strong className={styles.recordAmount}>{money(hundredths(r.total,BigInt(9999999))!,"AUD")}</strong><div className={styles.recordMeta}><span>{r.category}</span><span>{r.treatment}</span></div><div className={styles.titleRow}><small>Original retained · {r.businessPercent}% business use</small><Link href={`/upload/${doc.id}`} className={styles.textLink}>View source ↗</Link></div></article>; })}</div>}</section>
    {!!records.length && <section className={styles.panel} data-glow="true"><span className={styles.eyebrow}>THE SHAPE OF YOUR RECORDS</span><h2>Categories, at a glance.</h2><div className={styles.categoryBars}>{categories.map(category => { const count = records.filter(doc => doc.record!.category === category).length; return count ? <button key={category} onClick={() => setFilters(current => ({ ...current, category }))}><span>{category}</span><div aria-hidden="true"><i style={{ width: `${count / records.length * 100}%` }} /></div><strong>{count} record{count === 1 ? "" : "s"}</strong></button> : null; })}</div></section>}
    <p className={styles.footnote}>This view follows invoice dates. It is a financial organiser, not a lodged tax return or BAS. Original files remain separate from Excel exports. <a href="https://business.gov.au/finance/payments-and-invoicing/record-keeping" target="_blank" rel="noreferrer">Australian record-keeping guidance ↗</a></p>
  </AppShell>;
}
