"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import AppShell from "../components/app-shell";
import { useVault } from "../../lib/use-vault";
import { allocations, categories, financialYear } from "../../lib/domain/tax-record";
import { filterRecords } from "../../lib/domain/vault-filter";
import { hundredths } from "../../lib/domain/invoice-math";
import ProtectedExport from "../components/protected-export";
import { useWorkspace } from "../components/workspace-provider";
import { permitted } from "../../lib/server/permissions";
import { money } from "../components/money";
import styles from "../vault.module.css";
export default function RecordsPage() {
  const { documents, loading, error } = useVault();
  const [filters, setFilters] = useState({ year: "", query: "", kind: "", category: "" });
  const [view, setView] = useState<"cards" | "list">("cards"), [selected, setSelected] = useState<string[]>([]);
  const [imports, setImports] = useState<{ id: string; name: string; total: number; saved: number }[]>([]);
  const [exportScope, setExportScope] = useState("filtered"), [exportOpen, setExportOpen] = useState(false), [message, setMessage] = useState("");
  const canExport = permitted(useWorkspace()?.workspace.role || "", "records.export");
  const dialog = useRef<HTMLDialogElement>(null);
  useEffect(() => { const controller = new AbortController(); fetch("/api/vault/imports", { cache: "no-store", signal: controller.signal }).then(async response => { if (!response.ok) return []; return (await response.json()).imports; }).then(value => { if (!controller.signal.aborted) setImports(value); }).catch(() => {}); return () => controller.abort(); }, []);
  const records = filterRecords(documents, filters), review = documents.filter(doc => doc.status === "Review"), pending = imports.filter(value => value.saved < value.total);
  const years = [...new Set(documents.flatMap(doc => doc.record ? [financialYear(doc.record.issued)] : []))].sort().reverse();
  const visibleSelected = selected.filter(id => records.some(doc => doc.id === id));
  const all = filterRecords(documents, { year: "", query: "", kind: "", category: "" });
  const stats = records.reduce((total, doc) => { const r = doc.record!; if (r.kind === "Expense") total.expense += hundredths(r.total, BigInt(9999999))!; if (r.kind === "Income") total.income += hundredths(r.total, BigInt(9999999))!; total.credit += allocations(r).credit; return total; }, { expense: BigInt(0), income: BigInt(0), credit: BigInt(0) });
  const exportCount = exportScope === "all" ? all.length : exportScope === "selected" ? visibleSelected.length : records.length;
  const params = new URLSearchParams(exportScope === "all" ? {} : filters); if (exportScope === "selected") params.set("ids", visibleSelected.join(","));
  return <AppShell title="Invoice records" subtitle="Review, organise and share your records with your tax agent.">
    <Link href="/reports/documents" target="_blank" rel="noopener noreferrer" className={styles.documentAccess}>Documents in Reports <span aria-hidden="true">↗</span><span className={styles.srOnly}> (opens in a new tab)</span></Link>
    <div className={styles.titleRow}><span className={styles.muted}>Your records · AUD</span><div className={styles.actions}><details className={styles.addMenu}><summary className={styles.secondary}>Add records +</summary><div><Link href="/upload">Upload invoice</Link><Link href="/records/import">Import Excel workbook</Link></div></details>{canExport && <button className={styles.primary} disabled={loading || !!error || !all.length} onClick={() => { setExportScope(visibleSelected.length ? "selected" : "filtered"); setMessage(""); setExportOpen(true); dialog.current?.showModal(); }}>Export for tax agent ↓</button>}</div></div>
    {error && <p className={styles.notice} role="alert">{error}</p>}
    {message && !exportOpen && <p className={styles.notice} role="alert">{message}</p>}
    <section className={styles.stats} aria-label="Confirmed record totals">{[["Income",stats.income],["Expenses",stats.expense],["Selected GST credit",stats.credit]].map(([label,value]) => <div className={styles.panel} data-glow="true" key={String(label)}><span className={styles.tag}>{String(label)}</span><strong className={styles.statValue}>{money(value as bigint,"AUD")}</strong><small>{label === "Selected GST credit" ? "Based on your tax selections" : "Confirmed document totals"}</small></div>)}</section>
    {!!pending.length && <details className={styles.resumeImports}><summary>{pending.length} workbook import{pending.length > 1 ? "s" : ""} to finish</summary>{pending.map(value => <Link key={value.id} href={`/records/import/${value.id}`}>{value.name}<span>{value.total - value.saved} rows remaining · Resume →</span></Link>)}</details>}
    {!!review.length && <Link href="/upload" className={styles.reviewBanner}><span className={styles.pulse} /><span><strong>{review.length} invoice{review.length > 1 ? "s" : ""} waiting for review</strong><small>Not included in totals or exports yet.</small></span><span aria-hidden="true">↗</span></Link>}
    <section className={styles.panel} data-glow="true"><div className={`${styles.filters} ${styles.simpleFilters}`}><label>Search<input type="search" placeholder="Supplier, invoice or filename" value={filters.query} onChange={e => setFilters(current => ({ ...current, query: e.target.value }))} /></label><label>Financial year<select value={filters.year} onChange={e => setFilters(current => ({ ...current, year: e.target.value }))}><option value="">All financial years</option>{years.map(year => <option key={year}>{year}</option>)}</select></label></div>
    <details className={styles.filterDisclosure}><summary>More filters</summary><div className={styles.fields}><label>Type<select value={filters.kind} onChange={e => setFilters(current => ({ ...current, kind: e.target.value }))}><option value="">All types</option>{["Expense","Income","Personal"].map(kind => <option key={kind}>{kind}</option>)}</select></label><label>Category<select value={filters.category} onChange={e => setFilters(current => ({ ...current, category: e.target.value }))}><option value="">All categories</option>{categories.map(category => <option key={category}>{category}</option>)}</select></label></div></details>
    <div className={styles.titleRow}><span className={styles.tag}>{records.length} records{visibleSelected.length ? ` · ${visibleSelected.length} selected` : ""}</span><label className={styles.compactField}><span className={styles.srOnly}>Records view</span><select value={view} onChange={e => setView(e.target.value as typeof view)}><option value="cards">Card view</option><option value="list">List view</option></select></label></div>
    {loading ? <p role="status">Opening your records…</p> : !records.length ? <div className={styles.empty}><h2>{all.length ? "No matching records." : "Start with your first record."}</h2><p>{all.length ? "Adjust your search or filters." : "Upload an invoice or bring your existing records from Excel."}</p><Link href="/records/import" className={styles.secondary}>Import Excel →</Link></div> : <div className={view === "cards" ? styles.recordGrid : styles.recordList}>{records.map(doc => { const r = doc.record!; return <article className={styles.record} data-glow="true" key={doc.id}><div className={styles.titleRow}><span className={styles.tag}>{r.kind} · {financialYear(r.issued)}</span><label className={styles.selectRecord}><input aria-label={`Select invoice ${r.number}`} type="checkbox" checked={selected.includes(doc.id)} onChange={e => setSelected(current => e.target.checked ? [...current,doc.id] : current.filter(id => id !== doc.id))} />Select</label></div><h3>{r.supplier}</h3><p>{r.number} · {r.issued}</p><strong className={styles.recordAmount}>{money(hundredths(r.total,BigInt(9999999))!,"AUD")}</strong><div className={styles.recordMeta}><span>{r.category}</span><span>{r.treatment}</span></div><div className={styles.titleRow}><small>{doc.source ? `Excel · row ${doc.source.row}` : "Original retained"} · {r.businessPercent}% business use</small><Link href={`/upload/${doc.id}`} className={styles.textLink}>View record ↗</Link></div></article>; })}</div>}</section>
    {!!records.length && <details className={`${styles.panel} ${styles.details}`}><summary>Category breakdown</summary><div className={styles.categoryBars}>{categories.map(category => { const count = records.filter(doc => doc.record!.category === category).length; return count ? <button key={category} onClick={() => setFilters(current => ({ ...current, category }))}><span>{category}</span><div aria-hidden="true"><i style={{ width: `${count / records.length * 100}%` }} /></div><strong>{count}</strong></button> : null; })}</div></details>}
    <p className={styles.footnote}>Invoice-date records for tax-agent review. Supporting documents remain in the vault; this is not a submitted tax return or BAS.</p>
    {canExport && <dialog ref={dialog} className={styles.exportDialog} onClose={() => setExportOpen(false)}><div className={styles.titleRow}><h2>Export for your tax agent</h2><button className={styles.secondary} aria-label="Close export" onClick={() => dialog.current?.close()}>×</button></div><p className={styles.muted}>One Excel workbook with an overview, detailed records and a financial-year/category summary.</p><label className={styles.compactField}>Include<select value={exportScope} onChange={e => setExportScope(e.target.value)}><option value="filtered">Filtered records ({records.length})</option><option value="selected" disabled={!visibleSelected.length}>Selected records ({visibleSelected.length})</option><option value="all">All confirmed records ({all.length})</option></select></label><p className={styles.footnote}>{exportCount} records · AUD · original files remain separate</p><ProtectedExport href={`/api/vault/export?${params}`} filename="TCS-InvoiceFlow-tax-agent-records.xlsx" disabled={!exportCount} onDone={() => dialog.current?.close()}>Download .xlsx</ProtectedExport></dialog>}
  </AppShell>;
}
